In [1]:
import torch

In [2]:
t1=torch.tensor([1,2,3,4])
t2=torch.tensor([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

In [3]:
print("Tensor t1:\n",t1)
print("\nTensor t2:\n",t2)

Tensor t1:
 tensor([1, 2, 3, 4])

Tensor t2:
 tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]])


In [4]:
print("\nRank of t1:",len(t1.shape))
print("Rank of t2:",len(t2.shape))


Rank of t1: 1
Rank of t2: 2


In [5]:
import torch
import numpy as np

In [6]:
data1 = [1,2,3,4,5,6]
data2 = np.array([1.5,3.4,6.8,9.3,7.0,2.8])

In [7]:
t1 = torch.tensor(data1)
t2 = torch.Tensor(data1)
t3 = torch.as_tensor(data2)
t4 = torch.from_numpy(data2)

In [8]:
print("Tensor: ",t1,"Data type:",t1.dtype,"\n")
print("Tensor: ",t2,"Data type:",t2.dtype,"\n")
print("Tensor: ",t3,"Data type:",t3.dtype,"\n")
print("Tensor: ",t4,"Data type:",t4.dtype,"\n")

Tensor:  tensor([1, 2, 3, 4, 5, 6]) Data type: torch.int64 

Tensor:  tensor([1., 2., 3., 4., 5., 6.]) Data type: torch.float32 

Tensor:  tensor([1.5000, 3.4000, 6.8000, 9.3000, 7.0000, 2.8000], dtype=torch.float64) Data type: torch.float64 

Tensor:  tensor([1.5000, 3.4000, 6.8000, 9.3000, 7.0000, 2.8000], dtype=torch.float64) Data type: torch.float64 



In [9]:
import torch

In [10]:
t = torch.tensor([[1,2,3,4],[5,6,7,8],[9,10,11,12]])


In [11]:
print("Reshaping")
print(t.reshape(6,2))
print("\nResizing")
print(t.resize(2,6))
print("\nTrnsposing")
print(t.transpose(1,0))

Reshaping
tensor([[ 1,  2],
        [ 3,  4],
        [ 5,  6],
        [ 7,  8],
        [ 9, 10],
        [11, 12]])

Resizing
tensor([[ 1,  2,  3,  4,  5,  6],
        [ 7,  8,  9, 10, 11, 12]])

Trnsposing
tensor([[ 1,  5,  9],
        [ 2,  6, 10],
        [ 3,  7, 11],
        [ 4,  8, 12]])


C:\Python313\Lib\site-packages\torch\_tensor.py:1024: UserWarning: non-inplace resize is deprecated
  warnings.warn("non-inplace resize is deprecated")


In [12]:
import torch

In [13]:
t1 = torch.tensor([1,2,3,4])
t2 = torch.tensor([5,6,7,8])
print("tensor2 + tensor1")
print(torch.add(t2,t1))
print("\ntensor2 - tensor1")
print(torch.sub(t2,t1))
print("\ntensor2 * tensor1")
print(torch.mul(t2,t1))
print("\ntensor2 / tensor1")
print(torch.div(t2,t1))


tensor2 + tensor1
tensor([ 6,  8, 10, 12])

tensor2 - tensor1
tensor([4, 4, 4, 4])

tensor2 * tensor1
tensor([ 5, 12, 21, 32])

tensor2 / tensor1
tensor([5.0000, 3.0000, 2.3333, 2.0000])


In [14]:
import torch


In [15]:
t1 = torch.tensor(1.0, requires_grad=True)
t2 = torch.tensor(2.0, requires_grad=True)

In [16]:
z= 100*t1*t2
z.backward()
print("dz/dt1: ",t1.grad.data)
print("dz/dt2: ",t2.grad.data)

dz/dt1:  tensor(200.)
dz/dt2:  tensor(100.)
